### ISSUE TITLE
Transformation to a parallax foreground element?

### ISSUE THREAD

**Issue by AngelLestat** [mmkjony/enllax.js#13]
How can I apply a transformation to a parallax foreground element?
When I apply the parallax effect to one of my elements which are rotated and fliped, they lose those properties, I understand that the plugin overwrites the transform style, but I cant think in a solution to have both cases of transformations, parallax and flip working together.

The plugin is great, it is awesome even if this can not be made, thanks for the contribution.

**Comment by mmkjony** [comment]
You can use a parent wrapper (e.g. div) for your flipping/rotating element, add some css to match your design (if needed), and use parallax effect on that (parent wrapper). Thanks for your compliment.

**Comment by AngelLestat** [comment]
lol, I cant believe that after one hour thinking about it, I could not figure out the solution.   Sorry to bother you and thank you for the answer.  Have a nice day.
