### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by xApep** [mmkjony/enllax.js#2]
Is this working without inline attributes? (data-enllax-ratio=".5" data-enllax-type="forground").

This code doesn't do much:
    $('.parallax').enllax({
        type: 'background', // 'foreground'
        ratio: 0.5,
       direction: 'vertical' // 'horizontal'
    });

**Comment by mmkjony** [comment]
Hi! Thanks for your compliment.
Here, the main selector is a child element having a 'data-enllax-ratio' attribute. You only have to use this attribute to make it work. It may be blank, if you want to pass the value inside function. Other values can be set inside function, without inline attributes. Here's an example:

<div class="parallax">
    <div data-enllax-ratio=""> 
        Some contents
    </div>
</div>

<script>
    $('.parallax').enllax({
        type: 'background', // 'foreground'
        ratio: 0.5,
        direction: 'vertical' // 'horizontal'
    });
</script>

or you may simply use:

<script>
    $(window).enllax();
</script>

Your selector should be a parent element.

I'll try to solve the selector issue, to make it work without any inline attributes. Thanks for your support. :)
