### ISSUE TITLE
Parallax lags in chrome (Mac OS).

### ISSUE THREAD

**Issue by Mikkoun** [mmkjony/enllax.js#4]
This happens only when i use Mac OS. JQuery smooth scroll lib fixed it, but caused touchpad to act really weird so i had to dump that.

**Comment by VidalThemes** [comment]
@Mikkoun I was also experiencing stutter in Mac Chrome, I added the following to my container, and it eliminated it.

```
background-attachment: fixed;
transform: translate3d(0, 0, 0);
```

**Comment by mmkjony** [comment]
Please use another plugin named "SmoothScroll for websites". This plugin will help to solve this issue. As webkit browser's default scrolling is a little shaking. You can just include this script linked below:
https://cdnjs.cloudflare.com/ajax/libs/smoothscroll/1.4.4/SmoothScroll.min.js

Thanks for your support.
