### ISSUE TITLE
lagging on safari (mac)

### ISSUE THREAD

**Issue by pavita** [mmkjony/enllax.js#5]
Chorme and Firefox works fine but on safari it's lagging and shaking.

**Comment by piyushwalia** [comment]
Same issue occurring at my end also

**Comment by pepperstreet** [comment]
Hello, was about to open a new topic... same here: 
Not smooth on **Safari**. All layers/elements are kinda "jumpy".

(besides many thanks for the project and your efforts!)

**Comment by mmkjony** [comment]
Please use another plugin named "SmoothScroll for websites". This plugin will help to solve this issue. As webkit browser's default scrolling is a little shaking. You can just include this script linked below:
https://cdnjs.cloudflare.com/ajax/libs/smoothscroll/1.4.4/SmoothScroll.min.js

Thanks for your support.

**Comment by fourroses666** [comment]
Demo is lagging too even with SmoothScroll. Chrome and Firefox on Mac.
